<a href="https://colab.research.google.com/github/gumdropsteve/intro_to_python/blob/main/day_04/01_numpy_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py'>

In [11]:
# random array 3x3
np.random.rand(3, 3)

array([[0.89357444, 0.68223078, 0.90056958],
       [0.61821118, 0.18866134, 0.02322307],
       [0.59293357, 0.52425738, 0.09050618]])

In [12]:
np.random.rand(3, 3).shape

(3, 3)

In [13]:
np.random.rand(3, 3).size

9

In [33]:
np.random.randint(4, 10, (3))

array([7, 9, 4])

In [82]:
a = np.random.rand(3, 3)

b = np.random.randint(4, 10, (3))

a * b

array([[2.72161968, 2.82252525, 2.20245098],
       [0.3143866 , 5.98382915, 3.35964078],
       [1.37356232, 5.10890076, 3.74621384]])

## Matrix Multiplication with Numpy

In [85]:
a = np.matrix(np.random.rand(3, 3))

a

matrix([[0.80436609, 0.50589295, 0.08563389],
        [0.07043579, 0.24028082, 0.17489134],
        [0.48508186, 0.55265002, 0.51160052]])

In [86]:
b = np.matrix(np.random.rand(3, 1))

b

matrix([[0.81300779],
        [0.54448784],
        [0.90595459]])

In [87]:
a * b

matrix([[1.00698887],
        [0.34653844],
        [1.15877339]])

In [124]:
c = [np.random.rand(3, 1) for i in range(10)]

c = np.array(c)

c = np.matrix(c)  # note: matrix must be 2D

c.shape

(10, 3)

In [125]:
c.shape

(10, 3)

In [126]:
d = np.matrix([[i for i in range(10)] for i in range(3)])

d.shape

(3, 10)

In [127]:
c*d

matrix([[ 0.        ,  1.89396809,  3.78793618,  5.68190426,  7.57587235,
          9.46984044, 11.36380853, 13.25777662, 15.1517447 , 17.04571279],
        [ 0.        ,  2.3009145 ,  4.601829  ,  6.9027435 ,  9.203658  ,
         11.5045725 , 13.805487  , 16.1064015 , 18.407316  , 20.7082305 ],
        [ 0.        ,  1.75764858,  3.51529717,  5.27294575,  7.03059433,
          8.78824291, 10.5458915 , 12.30354008, 14.06118866, 15.81883724],
        [ 0.        ,  1.65549006,  3.31098012,  4.96647018,  6.62196024,
          8.2774503 ,  9.93294036, 11.58843042, 13.24392048, 14.89941054],
        [ 0.        ,  2.40590581,  4.81181163,  7.21771744,  9.62362326,
         12.02952907, 14.43543489, 16.8413407 , 19.24724652, 21.65315233],
        [ 0.        ,  2.31119236,  4.62238472,  6.93357708,  9.24476944,
         11.5559618 , 13.86715416, 16.17834652, 18.48953888, 20.80073124],
        [ 0.        ,  0.78781259,  1.57562517,  2.36343776,  3.15125034,
          3.93906293,  4.7268755

In [128]:
d

matrix([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Aside on list comprehension.

In [103]:
l = []

for i in range(10):
    l.append(i)

l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [105]:
l = [i for i in range(10)]

l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Computation on NumPy Arrays

In [130]:
w = np.random.randint(1, 10, size=(2, 3))
w

array([[2, 6, 4],
       [3, 3, 9]])

In [131]:
np.add.reduce(w)

array([ 5,  9, 13])

In [132]:
np.multiply.reduce(w)

array([ 6, 18, 36])

In [133]:
w * 5

array([[10, 30, 20],
       [15, 15, 45]])

In [134]:
w ** 5

array([[   32,  7776,  1024],
       [  243,   243, 59049]])

In [137]:
w // 5

array([[0, 1, 0],
       [0, 0, 1]])

In [138]:
w ** 5 // 5

array([[    6,  1555,   204],
       [   48,    48, 11809]])

In [139]:
w + 0.001

array([[2.001, 6.001, 4.001],
       [3.001, 3.001, 9.001]])

### Compairsons 

In [142]:
np.random.rand(3, 3) > np.random.rand(3, 3)

array([[False, False,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [143]:
np.random.rand(3, 3) <= np.random.rand(3, 3)

array([[False, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [144]:
np.random.rand(3, 3) != np.random.rand(3, 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [145]:
np.random.rand(3, 3) == np.random.rand(3, 3)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [150]:
# reduce possible outcomes to integers 1 & 2
np.random.randint(1, 3, size=(3, 3)) == np.random.randint(1, 3, size=(3, 3))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [146]:
np.random.randint(1, 3, size=(3, 3))

array([[1, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [162]:
# about 50%?
outcomes = []

for _ in range(1000):
    score = np.sum(np.random.randint(1, 3, size=(3, 3)) == np.random.randint(1, 3, size=(3, 3)))
    outcomes.append(score)


# np.mean(outcomes) / 9  # take mean of list
np.mean(np.array(outcomes)) / 9  # take mean of array

0.5006666666666667

In [168]:
# exact same thing with list comprehension
outcomes = [np.sum(np.random.randint(1, 3, size=(3, 3)) == np.random.randint(1, 3, size=(3, 3))) 
            for s in range(1000)]

np.mean(outcomes) / 9

0.4998888888888888