<a href="https://colab.research.google.com/github/gumdropsteve/intro_to_python/blob/day_04/day_04/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py'>

In [11]:
# random array 3x3
np.random.rand(3, 3)

array([[0.89357444, 0.68223078, 0.90056958],
       [0.61821118, 0.18866134, 0.02322307],
       [0.59293357, 0.52425738, 0.09050618]])

In [12]:
np.random.rand(3, 3).shape

(3, 3)

In [13]:
np.random.rand(3, 3).size

9

In [33]:
np.random.randint(4, 10, (3))

array([7, 9, 4])

In [34]:
a = np.random.rand(3, 3)

b = np.random.randint(4, 10, (3))

a * b

array([[2.36989935, 2.19589952, 4.37163559],
       [3.98278529, 2.9364996 , 2.32700047],
       [2.03056366, 1.52340606, 4.503763  ]])

## Matrix Multiplication with Numpy

In [35]:
a = np.matrix(np.random.rand(3, 3))

a

matrix([[0.50620257, 0.15289366, 0.56367934],
        [0.5716325 , 0.70817103, 0.06063075],
        [0.3075915 , 0.89570286, 0.06963805]])

In [36]:
b = np.matrix(np.random.rand(3, 1))

b

matrix([[0.35359449],
        [0.30346556],
        [0.44600272]])

In [37]:
a * b

matrix([[0.47679092],
        [0.4440731 ],
        [0.41163639]])

### Computation on NumPy Arrays

In [49]:
w = np.random.randint(1, 10, size=(2, 3))
w

array([[8, 1, 6],
       [7, 5, 1]])

In [50]:
np.add.reduce(w)

array([15,  6,  7])

In [51]:
np.multiply.reduce(w)

array([56,  5,  6])

### Compairsons 

In [52]:
np.random.rand(3, 3) > np.random.rand(3, 3)

array([[ True, False, False],
       [False, False, False],
       [False,  True, False]])

In [53]:
np.random.rand(3, 3) <= np.random.rand(3, 3)

array([[False, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [54]:
np.random.rand(3, 3) != np.random.rand(3, 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
np.random.rand(3, 3) == np.random.rand(3, 3)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [60]:
# reduce possible outcomes to integers 1 & 2
np.random.randint(1, 3, size=(3, 3)) == np.random.randint(1, 3, size=(3, 3))

array([[ True,  True, False],
       [False, False,  True],
       [ True, False,  True]])